// Code generated by "stringer -type=Lang"; DO NOT EDIT

package lingvo

import "fmt"

const (
	_Lang_name_0 = "Ch"
	_Lang_name_1 = "DaDeElEnEs"
	_Lang_name_2 = "Fr"
	_Lang_name_3 = "It"
	_Lang_name_4 = "Pl"
	_Lang_name_5 = "Ru"
	_Lang_name_6 = "Uk"
	_Lang_name_7 = "Kk"
	_Lang_name_8 = "Tt"
	_Lang_name_9 = "La"
)

var (
	_Lang_index_0 = [...]uint8{0, 2}
	_Lang_index_1 = [...]uint8{0, 2, 4, 6, 8, 10}
	_Lang_index_2 = [...]uint8{0, 2}
	_Lang_index_3 = [...]uint8{0, 2}
	_Lang_index_4 = [...]uint8{0, 2}
	_Lang_index_5 = [...]uint8{0, 2}
	_Lang_index_6 = [...]uint8{0, 2}
	_Lang_index_7 = [...]uint8{0, 2}
	_Lang_index_8 = [...]uint8{0, 2}
	_Lang_index_9 = [...]uint8{0, 2}
)

func (i Lang) String() string {
	switch {
	case i == 1028:
		return _Lang_name_0
	case 1030 <= i && i <= 1034:
		i -= 1030
		return _Lang_name_1[_Lang_index_1[i]:_Lang_index_1[i+1]]
	case i == 1036:
		return _Lang_name_2
	case i == 1040:
		return _Lang_name_3
	case i == 1045:
		return _Lang_name_4
	case i == 1049:
		return _Lang_name_5
	case i == 1058:
		return _Lang_name_6
	case i == 1087:
		return _Lang_name_7
	case i == 1092:
		return _Lang_name_8
	case i == 1142:
		return _Lang_name_9
	default:
		return fmt.Sprintf("Lang(%d)", i)
	}
}
