// Code generated by "stringer -type=NodeType"; DO NOT EDIT

package lingvo

import "fmt"

const _NodeType_name = "CommentParagraphTextListListItemExamplesExampleItemExampleCardRefsCardRefItemCardRefTranscriptionAbbrevCaptionSoundRefUnsupported"

var _NodeType_index = [...]uint8{0, 7, 16, 20, 24, 32, 40, 51, 58, 66, 77, 84, 97, 103, 110, 115, 118, 129}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
